import { expect, test } from '@playwright/test';

import { EVIDENCE } from '../app/_lib/links';

/**
 * `/evidence/<path>` is where every "read the transcript yourself" link on the site lands while
 * the repository has no public remote. It reads the file off disk at request time and the path it
 * joins is computed, not literal — which means a bundler cannot see it, and a serverless
 * deployment will happily ship the route without the files it exists to serve. Locally everything
 * resolves; in production every link answers "allowlisted but not present in this checkout".
 *
 * That is a dead link on the one surface whose entire job is being checkable, so it is pinned
 * here: every allowlisted path must return 200 and real bytes, and anything off the list must
 * still 404. `next.config.mjs` names the same files under `outputFileTracingIncludes`; if the two
 * lists drift, this fails.
 */

test('every allowlisted evidence file is served, with content', async ({ request }) => {
  expect(EVIDENCE.length).toBeGreaterThan(10);

  for (const path of EVIDENCE) {
    const res = await request.get(`/evidence/${path}`);
    expect(res.status(), `${path} must be readable`).toBe(200);
    const body = await res.text();
    expect(body.length, `${path} must not be empty`).toBeGreaterThan(64);
    expect(body, `${path} must not be the not-present message`).not.toContain(
      'allowlisted but not present',
    );
  }
});

test('the evidence route is an allowlist, not a file browser', async ({ request }) => {
  for (const path of ['package.json', '.env', '../package.json', 'src/config.ts']) {
    const res = await request.get(`/evidence/${path}`);
    expect(res.status(), `${path} must not be readable`).toBe(404);
  }
});

test('the committed transcript carries the surface tally the docs claim', async ({ request }) => {
  // README.md and JUDGE.md both promise the count is printed by the run rather than transcribed.
  // If a transcript is regenerated by a build that lost the instrumentation, this catches it.
  const res = await request.get('/evidence/docs/pipeline-output.txt');
  expect(res.status()).toBe(200);
  const transcript = await res.text();
  expect(transcript).toContain('ATTESTCOIN SURFACES EXERCISED THIS RUN: 30');
  expect(transcript).toMatch(/INativeQueryVerifier\.calculateTxIndex/);
});
